name: deploy-manifest

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Authenticate with Google Cloud and configure kubectl
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Download kubectl
      - name: Download kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y kubectl

      # Apply Kubernetes manifests
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f infra/k8s
          kubectl apply -f infra/k8s-prod